# Generated by Django 4.0.7 on 2022-09-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_secret',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_price',
            field=models.IntegerField(default=0),
        ),
    ]
