# Generated by Django 4.0.7 on 2022-09-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_reset_password_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_password_secret',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
