# Generated by Django 4.0.7 on 2022-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_reset_password_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='initial_price',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_password_secret',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
