# Generated by Django 4.0.7 on 2022-10-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_product_initial_price_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_password_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
