# Generated by Django 4.0.8 on 2022-11-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restriction',
            field=models.IntegerField(default=300, null=True),
        ),
    ]
