# Generated by Django 4.0.7 on 2022-09-02 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('market', models.CharField(blank=True, max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('has_stock', models.BooleanField(blank=True)),
                ('current_price', models.IntegerField(blank=True)),
                ('initial_price', models.IntegerField(blank=True)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
